import ../consts

const
  ESP_ERR_ESP_TLS_BASE* = 0x8000

const
  ESP_ERR_ESP_TLS_CANNOT_RESOLVE_HOSTNAME* = (ESP_ERR_ESP_TLS_BASE + 0x01)
  ESP_ERR_ESP_TLS_CANNOT_CREATE_SOCKET* = (ESP_ERR_ESP_TLS_BASE + 0x02)
  ESP_ERR_ESP_TLS_UNSUPPORTED_PROTOCOL_FAMILY* = (ESP_ERR_ESP_TLS_BASE + 0x03)
  ESP_ERR_ESP_TLS_FAILED_CONNECT_TO_HOST* = (ESP_ERR_ESP_TLS_BASE + 0x04)
  ESP_ERR_ESP_TLS_SOCKET_SETOPT_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x05)
  ESP_ERR_ESP_TLS_CONNECTION_TIMEOUT* = (ESP_ERR_ESP_TLS_BASE + 0x06)
  ESP_ERR_ESP_TLS_SE_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x07)
  ESP_ERR_ESP_TLS_TCP_CLOSED_FIN* = (ESP_ERR_ESP_TLS_BASE + 0x08)

const
  ESP_ERR_MBEDTLS_CERT_PARTLY_OK* = (ESP_ERR_ESP_TLS_BASE + 0x10)
  ESP_ERR_MBEDTLS_CTR_DRBG_SEED_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x11)
  ESP_ERR_MBEDTLS_SSL_SET_HOSTNAME_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x12)
  ESP_ERR_MBEDTLS_SSL_CONFIG_DEFAULTS_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x13)
  ESP_ERR_MBEDTLS_SSL_CONF_ALPN_PROTOCOLS_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x14)
  ESP_ERR_MBEDTLS_X509_CRT_PARSE_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x15)
  ESP_ERR_MBEDTLS_SSL_CONF_OWN_CERT_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x16)
  ESP_ERR_MBEDTLS_SSL_SETUP_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x17)
  ESP_ERR_MBEDTLS_SSL_WRITE_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x18)
  ESP_ERR_MBEDTLS_PK_PARSE_KEY_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x19)
  ESP_ERR_MBEDTLS_SSL_HANDSHAKE_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x1A)
  ESP_ERR_MBEDTLS_SSL_CONF_PSK_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x1B)
  ESP_ERR_MBEDTLS_SSL_TICKET_SETUP_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x1C)

const
  ESP_ERR_WOLFSSL_SSL_SET_HOSTNAME_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x31)
  ESP_ERR_WOLFSSL_SSL_CONF_ALPN_PROTOCOLS_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x32)
  ESP_ERR_WOLFSSL_CERT_VERIFY_SETUP_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x33)
  ESP_ERR_WOLFSSL_KEY_VERIFY_SETUP_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x34)
  ESP_ERR_WOLFSSL_SSL_HANDSHAKE_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x35)
  ESP_ERR_WOLFSSL_CTX_SETUP_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x36)
  ESP_ERR_WOLFSSL_SSL_SETUP_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x37)
  ESP_ERR_WOLFSSL_SSL_WRITE_FAILED* = (ESP_ERR_ESP_TLS_BASE + 0x38)

when defined(CONFIG_ESP_TLS_USING_MBEDTLS):
  const
    ESP_TLS_ERR_SSL_WANT_READ* = MBEDTLS_ERR_SSL_WANT_READ
    ESP_TLS_ERR_SSL_WANT_WRITE* = MBEDTLS_ERR_SSL_WANT_WRITE
    ESP_TLS_ERR_SSL_TIMEOUT* = MBEDTLS_ERR_SSL_TIMEOUT
elif defined(CONFIG_ESP_TLS_USING_WOLFSSL):
  const
    ESP_TLS_ERR_SSL_WANT_READ* = -0x6900
    ESP_TLS_ERR_SSL_WANT_WRITE* = -0x6880
    ESP_TLS_ERR_SSL_TIMEOUT* = WOLFSSL_CBIO_ERR_TIMEOUT

type
  esp_tls_last_error_t* {.importc: "esp_tls_last_error_t",
                         header: "esp_tls_errors.h", bycopy.} = object
    last_error* {.importc: "last_error".}: esp_err_t
    esp_tls_error_code* {.importc: "esp_tls_error_code".}: cint
    esp_tls_flags* {.importc: "esp_tls_flags".}: cint

type
  esp_tls_error_type_t* {.size: sizeof(cint).} = enum
    ESP_TLS_ERR_TYPE_UNKNOWN = 0, ESP_TLS_ERR_TYPE_SYSTEM, ESP_TLS_ERR_TYPE_MBEDTLS,
    ESP_TLS_ERR_TYPE_MBEDTLS_CERT_FLAGS, ESP_TLS_ERR_TYPE_ESP,
    ESP_TLS_ERR_TYPE_WOLFSSL, ESP_TLS_ERR_TYPE_WOLFSSL_CERT_FLAGS,
    ESP_TLS_ERR_TYPE_MAX
  esp_tls_error_handle_t* = ptr esp_tls_last_error_t