ARG ESP_IDF_VERSION=4.4
ARG NIM_VERSION=1.6.20
ARG IMAGE=ghcr.io/embeddednim/esp-idf:${ESP_IDF_VERSION}-nim_${NIM_VERSION}-latest

FROM $IMAGE AS build

COPY . /app/

WORKDIR /app/
RUN nim -v
RUN nimble install -y

RUN : \
  && nimble test
